### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by solhuebner** [LordZero-0o/Galactea#1]
Please add a license :)

**Comment by LordZero-0o** [comment]
Added :)

**Comment by solhuebner** [comment]
> Added :)

Thanks :) But would you mind changing it to LGPL or something else?

The problem with GPL is that it is tough to use as it forces you to open source anything while LGPL keeps your part open but we are more flexible on our end ;)

This article is relatively good at explaining it: https://en.wikipedia.org/wiki/GNU_Lesser_General_Public_License

Most Arduboy games go either with MIT or BSD-3-Clause for that reason.

Regards

**Comment by LordZero-0o** [comment]
I think its done

**Comment by solhuebner** [comment]
Great. Thanks!
